# Generated by Django 3.0.5 on 2020-04-08 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_auto_20200408_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='favs',
            field=models.ManyToManyField(blank=True, related_name='favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
